last_change = 2026-09-29T14:51:29.716269Z
addr = 0x299740
size = 0x1350
name = "CNetChan_ParseMessagesDemoInternal"
type = "long long"

[header]
name = "CNetChan_ParseMessagesDemoInternal"
addr = 0x299740
type = "long long"

[header.args]
