last_change = 2026-09-29T14:51:29.716290Z
addr = 0x2b1ea0
size = 0x72
name = "CNetworkMessages_DeallocateNetMessageAbstract"
type = "void"

[header]
name = "CNetworkMessages_DeallocateNetMessageAbstract"
addr = 0x2b1ea0
type = "void"

[header.args]
