last_change = 2026-09-29T14:51:29.716302Z
addr = 0x2b2d60
size = 0x61b
name = "CNetworkMessages_RegisterNetworkFieldSerializer"
type = "long long"

[header]
name = "CNetworkMessages_RegisterNetworkFieldSerializer"
addr = 0x2b2d60
type = "long long"

[header.args]
