last_change = 2026-09-29T14:51:30.699443Z
addr = 0x2bb040
size = 0xd50
name = "CNetworkMessages_RegisterNetworkFieldChangeCallbackInternal"
type = "long long"

[header]
name = "CNetworkMessages_RegisterNetworkFieldChangeCallbackInternal"
addr = 0x2bb040
type = "long long"

[header.args]
