last_change = 2026-09-29T14:51:29.716294Z
addr = 0x2b24a0
size = 0xfa
name = "CNetworkMessages_RegisterFieldChangeCallbackPriority"
type = "long long"

[header]
name = "CNetworkMessages_RegisterFieldChangeCallbackPriority"
addr = 0x2b24a0
type = "long long"

[header.args]
