last_change = 2026-09-29T14:51:29.716340Z
addr = 0x2dc6e0
size = 0x39f
name = "CNetworkSystem_OpenSocket"
type = "bool"

[header]
name = "CNetworkSystem_OpenSocket"
addr = 0x2dc6e0
type = "bool"

[header.args]
