last_change = 2026-09-29T14:51:29.716332Z
addr = 0x2d28c0
size = 0x3b
name = "CNetworkSystem_GetUDPPort"
type = "long long"

[header]
name = "CNetworkSystem_GetUDPPort"
addr = 0x2d28c0
type = "long long"

[header.args]
