last_change = 2026-09-29T14:51:29.716354Z
addr = 0x2ea6a0
size = 0xbe5
name = "CNetworkSystem_PollSocket"
type = "long long"

[header]
name = "CNetworkSystem_PollSocket"
addr = 0x2ea6a0
type = "long long"

[header.args]
